### ISSUE TITLE
InfluxDBDataSource doesn't work if retencion policy is not default

### ISSUE THREAD

**Issue by BorisOsipov** [MarathonLabs/marathon#296]
**Issue:**
I have following config
```
...
retentionPolicyConfiguration:
      name: "rpMarathonTest"
      duration: "90d"
      shardDuration: "1h"
      replicationFactor: 1
      isDefault: false
...
```
For all tests(for second and next runs) I recieve in logs 
```
main @coroutine#12] <InfluxMetricsProvider> No success rate found for <com.testName>. Using 0 i.e. fails all the time
```
Sorting doesn't work.

**Investigations:**

When marathon read data for success rate sorting it executes query(frm docker log)
```
service=query query="SELECT mean(success) FROM marathon.autogen.tests WHERE time >= '2019-11-11T09:26:53.590Z' GROUP BY testname"
```

Pay attention to `FROM marathon.autogen.tests` - it is wrong. It should use my RP `rpMarathonTest`

P.S. Seems it is because query doesn't use correct from clause here 
https://github.com/Malinskiy/marathon/blob/4e3368dc12b854df36416be39c0056b2f4469792/core/src/main/kotlin/com/malinskiy/marathon/analytics/metrics/remote/influx/InfluxDBDataSource.kt#L32-L40
