### ISSUE TITLE
How to run a single test method?

### ISSUE THREAD

**Issue by ZakTaccardi** [MarathonLabs/marathon#354]
Hi - what's the correct way to instruct marathon to run a single test functions?

I see [testClassRegex](https://malinskiy.github.io/marathon/doc/options.html#test-class-regular-expression) - but no information on how to use this regex to target a specific test and method.

use case: 
  - I often like to use Spoon to create a report for a single test

If the regex does support this already, it would be great to make this clear in the docs

**Comment by BorisOsipov** [comment]
@ZakTaccardi

```
filteringConfiguration:
  whitelist:
  - type: "method"
    regex: ".*"
```

Also see https://malinskiy.github.io/marathon/doc/configuration.html
