### ISSUE TITLE
Trouble pushing results to influx DB

### ISSUE THREAD

**Issue by sparepal** [MarathonLabs/marathon#371]
```
name: "sample-app tests"
outputDir: "./marathon"
analyticsConfiguration:
  influx:
    url: "http://localhost:8086"
    user: "root"
    password: "root"
    dbName: "marathon"
    retentionPolicyConfiguration:
      name: "rpMarathonTest"
      duration: "90d"
      shardDuration: "1h"
      replicationFactor: 5
      isDefault: false
```
INFO: <-- 500 Internal Server Error http://localhost:8086/write?db=marathon&rp=rpMarathon&precision=n&consistency=one

Here is the config I set to push the results to DB. In the logs while running the tests I see the POST requests being made to push the results to the DB amd then an error pops up due to which obviously when I SELECT * from rpMarathonTest I do not get any results.

 Is there something I am missing?
