### ISSUE TITLE
ADAM reports empty JUnit reports with a negative test duration

### ISSUE THREAD

**Issue by saim80** [MarathonLabs/marathon#429]
**Describe the bug**
Run the test with ADAM. Have some incomplete tests.
Final JUnit reports contain no log or stack trace. It also contains a negative test duration.
The reports are corrected once I stop using ADAM.

**To Reproduce**
Steps to reproduce the behaviour:
1. Run Tests.
2. Not sure if related but I had some incomplete tests.
3. See JUnit reports after the test run.

+ I noticed device timed out and retried but I'm not sure if this is related because all test failure logs are gone. Even without any device time out.

```
name: "Mighty CI Run"
outputDir: "./test-result"
poolingStrategy:
- type: "omni"
shardingStrategy:
  type: "parallel"
sortingStrategy:
  type: "no-sorting"
batchingStrategy:
  type: "isolate"
uncompletedTestRetryQuota: 100
testClassRegexes:
  - ".*"
vendorConfiguration:
  type: "Android"
  applicationApk: "app/build/outputs/apk/mightybellStaging/debug/app-mightybellStaging-debug.apk"
  testApplicationApk: "app/build/outputs/apk/androidTest/mightybellStaging/debug/app-mightybellStaging-debug-androidTest.apk"
  applicationPmClear: true
  testApplicationPmClear: true
  screenRecordConfiguration:
    preferableRecorderType: "video"
    videoConfiguration:
      enabled: true
      width: 1080
      height: 1920
      bitrateMbps: 2
      timeLimit: 1200
    screenshotConfiguration:
      enabled: true
      width: 1080
      height: 1920
      delayMs: 1000
```

**Expected behavior**
Proper failure logs.

**Logs and reports**
![Screen Shot 2020-12-25 at 8 37 57 PM](https://user-images.githubusercontent.com/316606/103144118-43e45700-46f2-11eb-897b-3c24979ea540.png)

[archive(1).zip](https://github.com/Malinskiy/marathon/files/5742577/archive.1.zip)

**Devices (please complete the following information):**
 - Device: Pixel2 Emulator
 - OS: Android API 26

**Additional context**
N/A
