### ISSUE TITLE
Batching strategy has 5 times as many incomplete tests as complete tests

### ISSUE THREAD

**Issue by smugleafdev** [MarathonLabs/marathon#500]
When running with batching strategy, there are many incomplete tests. In a run with <300 tests, there were >1600 incomplete tests:

```
288 passed, 0 failed, 0 ignored tests
Raw: 288 passed, 3 failed, 0 ignored, 1611 incomplete tests
```

**To Reproduce**
````yaml
batchingStrategy:
  type: "fixed-size"
  size: 10
  durationMillis: 200000
  percentile: 80.0
  timeLimit: "-PT1H"
  lastMileLength: 10
````
My setup is running Android UI Espresso tests on three emulators and running Marathon v0.7.0 from the CLI.

**Expected behavior**
I would expect an amount of incomplete tests to be a fraction of the total tests, and not several times the total amount.

**Additional context**
According to the Allure report, all the incomplete tests are at the end of a batch, and incomplete tests stop happening in the last few batches.
