### ISSUE TITLE
Enhanced device filter

### ISSUE THREAD

**Issue by mabae** [MarathonLabs/marathon#526]
**Is your feature request related to a problem? Please describe.**
Device filtering is currently possible in the Gradle plugin based on the serial number only.

**Describe the solution you'd like**
A filtering on further device attributes, such as model, with a syntax similar to the `filteringConfiguration`. For example:
Kotlin DSL
```
deviceFilteringConfiguration {
  allowlist {
    add(DeviceSerialFilter("A.*".toRegex()))
  }
  blocklist {
    add(DeviceModelFilter("^B.*".toRegex()))
  }
}
```
YAML:
```
deviceFilteringConfiguration:
allowlist:
  - type: "serial"
    regex: "A.*"
blocklist:
  - type: "model"
    regex: "^B.*"
```

**Describe alternatives you've considered**
none

**Additional context**
Parameters deprecated by this enhancement: includeSerialRegexes, excludeSerialRegexes.
