### ISSUE TITLE
Marathon ignoring InfluxDB config

### ISSUE THREAD

**Issue by smugleafdev** [MarathonLabs/marathon#596]
I created a new empty InfluxDB 1.8 database and pointed Marathon to it from my Marathonfile as the docs instructed, but nothing happens. With debug on, I don't see it doing anything with InfluxDB. Otherwise, I'm able to run Marathon fine.

Am I missing something?

Marathon v0.6.5

```yaml
analyticsConfiguration:
  type: "influxdb"
  url: "https://<censored>"
  user: "<censored>"
  password: "<censored>"
  dbName: "marathonDB"
```

**Comment by Malinskiy** [comment]
@smugleafdev I believe you're trying to use the new configuration format from 0.7.0 in 0.6.5. the structure of the analytics configuration had to be changed in order to support simple wrapper rewrite of the gradle plugin.

I suggest you upgrade to 0.7.0 or I can provide a configuration for 0.6.5 if you need it

**Comment by Malinskiy** [comment]
Here is the sample of configuration that should work for 0.6.5:
```yaml
analyticsConfiguration:
  influx:
    url: "http://influx.svc.cluster.local:8086"
    user: "root"
    password: "root"
    dbName: "marathon"
```

The current way how docs are published only allows us to show docs for the latest version. If you have any idea on how to publish multiple versions using jekyll - feel free to suggest. I know it hurts the user experience.
