### ISSUE TITLE
Analytics Configuration randomly breaks batching

### ISSUE THREAD

**Issue by smugleafdev** [MarathonLabs/marathon#607]
**Describe the bug**
Batching of tests often stops about halfway into a test run. See screenshot.

I have InfluxDB setup and Marathon sending data to it. No sorting strategy, no changes to my batching strategy. Just analytics config set up.

Tried with 0.6.5 and 0.7.0, didn't notice a difference.

![Screen Shot 2022-02-08 at 8 10 29 AM](https://user-images.githubusercontent.com/20119855/153435498-d552d244-ba90-404e-8471-bc3b4ed2371e.png)

**To Reproduce**
Steps to reproduce the behavior for 0.7.0:

```yaml
retryStrategy:
  type: "fixed-quota"
  totalAllowedRetryQuota: 100
  retryPerTestQuota: 3
batchingStrategy:
  type: "fixed-size"
  size: 10
  durationMillis: 200000
  percentile: 80.0
  timeLimit: "-PT1H"
  lastMileLength: 10
analyticsConfiguration:
  type: "influxdb"
  url: "http://<censored>"
  user: "<censored>"
  password: "<censored>"
  dbName: "<censored>"
  retentionPolicyConfiguration:
    name: "rpMarathon"
    duration: "60d"
    shardDuration: "1h"
    replicationFactor: 5
    isDefault: false
```

If I comment out the analyticsConfiguration block, batching returns to normal.

**Expected behavior**
Batching should work the whole time.

Healthy run without analyticsConfiguration:
![Screen Shot 2022-02-11 at 8 12 58 AM](https://user-images.githubusercontent.com/20119855/153617160-0fc7a25f-4194-475b-91ec-8c422bee2d03.png)

**Devices:**
Android Emulators API 28 Pixel 2 skins
