### ISSUE TITLE
Hours are not displayed in the duration field in the report

### ISSUE THREAD

**Issue by pisanyialeksei** [MarathonLabs/marathon#687]
**Describe the bug**
Hours are not displayed in the duration field in the report (index.html page)
Duration field have the format like mm:ss.ms

**To Reproduce**
Steps to reproduce the behaviour:
1. Full configuration
```
name: "Tests"
outputDir: "app/build/reports/marathon"
poolingStrategy:
  type: "device-model"
filteringConfiguration:
  allowlist:
    - type: ${FILTER_TYPE}
      regex: ${REGEX}
  blocklist:
    - type: "package"
      regex: "***"
    - type: "fully-qualified-class-name"
      values:
        - "***"
    - type: "fully-qualified-class-name"
      values:
        - "***"
retryStrategy:
  type: "fixed-quota"
  totalAllowedRetryQuota: 45
  retryPerTestQuota: 2
vendorConfiguration:
  type: "Android"
  vendor: ADAM
  timeoutConfiguration:
    screencapturer: "PT10S"
    install: "PT5M"
  installOptions: "-t"
  applicationApk: "***"
  testApplicationApk: "***"
  applicationPmClear: true
  testApplicationPmClear: true
  allureConfiguration:
    enabled: true
```
2. Any additional information about the device provider (devices that were stuck, etc.)
Usual testruns

**Expected behavior**
The duration field should have the format hh:mm:ss

**Logs and reports**
<img width="1420" alt="1" src="https://user-images.githubusercontent.com/63617853/191193467-964136af-730f-4f26-83dd-73b8e4a133c0.png">
<img width="805" alt="2" src="https://user-images.githubusercontent.com/63617853/191193504-02b53ade-2872-436f-8132-53fb31d6ac4d.png">

**Devices (please complete the following information):**
Different real Android devices

**Additional context**
Same in Chrome, Yandex and Safari browsers
