### ISSUE TITLE
No Test cases found while using adam as vendor

### ISSUE THREAD

**Issue by madept** [MarathonLabs/marathon#773]
Hi,

I am getting following exception while using adam as vendor

``` 
If you need test annotations retrieval, remote test parser requires additional setup see https://marathonlabs.github.io/marathon/ven/android.html#test-parser
E 05:42:14.023 [main @coroutine#1] <com.malinskiy.marathon.Marathon> com.malinskiy.marathon.exceptions.NoTestCasesFoundException: No tests cases were found
```

Here is my marathonfile Generated from gradle plugin. I am using gradle plugin and my test cases are cucumber bases, earlier I was using spoon and it was working fine.

Also when i use ddmlib, it runs non UI test only. Please help me to migrate to marathon

Marathonfile

```yaml
name: "Marathon Tests"
outputDir: "/Users/kumark56/.gradle/daemon/7.4.2/build/reports/marathon/configDevAndroidTest"
outputConfiguration:
  maxPath: 1024
analyticsConfiguration:
  type: "disabled"
poolingStrategy:
  type: "omni"
shardingStrategy:
  type: "count"
  count: 5
sortingStrategy:
  type: "no-sorting"
batchingStrategy:
  type: "isolate"
flakinessStrategy:
  type: "ignore"
retryStrategy:
  type: "fixed-quota"
  totalAllowedRetryQuota: 100
  retryPerTestQuota: 3
filteringConfiguration:
  allowlist: []
  blocklist: []
ignoreFailures: false
isCodeCoverageEnabled: false
fallbackToScreenshots: false
strictMode: false
uncompletedTestRetryQuota: 100
testClassRegexes:
- ".*"
includeSerialRegexes: []
excludeSerialRegexes: []
testBatchTimeoutMillis: 1800000
testOutputTimeoutMillis: 130000
debug: true
screenRecordingPolicy: "ON_FAILURE"
vendorConfiguration:
  type: "Android"
  vendor: "DDMLIB"
  androidSdk: "/Users/kumark56/Library/Android/sdk"
  outputs:
  - application: "<path>/xxx-Next-4.57.0.0000-config-dev.apk"
    testApplication: "<path>/xxx-Next-4.57.0.0000-config-dev-androidTest.apk"
  autoGrantPermission: true
  instrumentationArgs: {}
  applicationPmClear: false
  testApplicationPmClear: false
  adbInitTimeoutMillis: 30000
  installOptions: ""
  serialStrategy: "AUTOMATIC"
  screenRecordConfiguration:
    videoConfiguration:
      enabled: true
      width: 720
      height: 1280
      bitrateMbps: 1
      timeLimit: 180
      timeLimitUnits: "SECONDS"
    screenshotConfiguration:
      enabled: true
      width: 720
      height: 1280
      delayMs: 500
  waitForDevicesTimeoutMillis: 30000
  allureConfiguration:
    enabled: false
    relativeResultsDirectory: "/files/allure-results"
    pathRoot: "APP_DATA"
  timeoutConfiguration:
    shell: 20.000000000
    listFiles: 20.000000000
    pushFile: 60.000000000
    pushFolder: 60.000000000
    pullFile: 30.000000000
    uninstall: 20.000000000
    install: 20.000000000
    screenrecorder: 200.000000000
    screencapturer: 0.300000000
    socketIdleTimeout: 30.000000000
    portForward: 20.000000000
  fileSyncConfiguration:
    pull: []
    push: []
  threadingConfiguration:
    bootWaitingThreads: 4
    adbIoThreads: 4
  testParserConfiguration:
    type: "remote"
    instrumentationArgs:
      listener: "com.malinskiy.adam.junit4.android.listener.TestAnnotationProducer"
  testAccessConfiguration:
    adb: false
    grpc: false
    console: false
    consoleToken: ""
  adbServers:
  - host: "127.0.0.1"
    port: 5037
  disableWindowAnimation: true
analyticsTracking: false
deviceInitializationTimeoutMillis: 180000
```

**Comment by Malinskiy** [comment]
Hey @madept.

I don't think your issue has anything to do with the adam vs ddmlib. 

First, please migrate to the latest version 0.8.0, which has only adam.
Second, please read the section of the docs on remote test parser and the requirements: https://docs.marathonlabs.io/android/configure#test-parser

From what you're describing above, you just added the 
```
    instrumentationArgs:
      listener: "com.malinskiy.adam.junit4.android.listener.TestAnnotationProducer"
```

without reading the docs first. Did you add the `androidTestImplementation` scoped dependency as described? If you don't need the annotations (and I assume you don't even have them for cucumber) then just remove the listener.

I'm not sure specifying a non-existent listener is supported. The `am instrument` execution is unlikely to even start unless listener exists in the classpath: the test parsing run likely just crashes without printing any tests, hence your `no test cases found` error.

For context on why you see only non-cucumber-UI tests: spoon is rudimentary in the test scheduling, it starts unknown tests and just reacts to events coming from the test execution. Marathon on the other hand plans the test execution which means marathon has to get a list of tests expected to run first. Since the tests executed by cucumber are generated on-the-fly during execution remote test parser is the only option for you to get the list of expected tests to run. Bytecode analysis will not yield any results (this is what the default option using local test parser is using).

**Comment by madept** [comment]
Thanks for the reply,
I have already added following to gradle
    androidTestImplementation 'com.malinskiy.adam:android-junit4-test-annotation-producer:0.5.0'
<img width="914" alt="Screenshot 2023-03-16 at 7 47 47 AM" src="https://user-images.githubusercontent.com/5476753/225492718-4a6c1622-dcdb-437f-a188-56b95faa102a.png">

regarding the document, it provides only these two things to be added which i already did. 

I need the annotation and using kheera as runner. Also 0.8.0 does not seems to be in mavencentral yet. Can you please confirm ? latest version i see is 0.7.6 only

Error I am getting: 

xxx-Next-4.57.0.0000-config-dev-androidTest.apk did not report any test annotations. If you need test annotations retrieval, remote test parser requires additional setup see https://marathonlabs.github.io/marathon/ven/android.html#test-parser
E 09:47:44.149 [main @coroutine#1] <com.malinskiy.marathon.Marathon> com.malinskiy.marathon.exceptions.NoTestCasesFoundException: No tests cases were found

**Comment by Malinskiy** [comment]
I haven't worked with [kheera](https://github.com/andrewjc/kheera-testrunner-android), it was also last updated 5-6 years ago, and I'm not sure it supports the `-e log true` which is essential for remote test parsing.

If your test run didn't report any test annotations with the additional lib then the run likely just crashes. To investigate if that's the case please run something like `am instrument -w -r -e log true -e listener com.malinskiy.adam.junit4.android.listener.TestAnnotationProducer com.example.test/androidx.test.runner.AndroidJUnitRunner` on the target Android device via adb shell replacing the test package `com.example.test` and the test runner `androidx.test.runner.AndroidJUnitRunner` with the ones used in your application. This should produce annotations similar to https://github.com/Malinskiy/adam/blob/master/android-junit4-test-annotation-producer/src/main/kotlin/com/malinskiy/adam/junit4/android/listener/TestAnnotationProducer.kt#L26. Maybe we can find a clue in the error of the command if you run it manually.

0.8.0 is out since yesterday: https://plugins.gradle.org/plugin/com.malinskiy.marathon. There is some migration from the old id though since it's now an official gradle plugin distributed using plugins.gradle.org

**Comment by madept** [comment]
I tried following 
adb shell am instrument -w -r -e log true  -e listener com.malinskiy.adam.junit4.android.listener.TestAnnotationProducer <xx>.test/<xxx>.runner.KheeraJUnitRunner  and it produces following on command line

.....
INSTRUMENTATION_STATUS_CODE: 1
INSTRUMENTATION_STATUS: class=SomeClass
INSTRUMENTATION_STATUS: numtests=39
INSTRUMENTATION_STATUS: test=Try to make a xyz Example No.1
......

to my suprise. initially it gave process crashed and then i tried with -e perf true along with -e log true as per https://gist.github.com/tsohr/5711945 then it started providing metric , then i tried without -e perf true , then also it provided metric

After this i again tried running marathon and it failed, I tried to run it from the same command line where above metric is generated.

Any thing you can suggest

**Comment by Malinskiy** [comment]
perf true is not a solution to the flakiness of your run. On the other hand, if it works with `-e perf true` you can put those arguments into the test parsing command using `instrumentationArgs`, e.g.:

```
  testParserConfiguration:
    type: "remote"
    instrumentationArgs:
      listener: "com.malinskiy.adam.junit4.android.listener.TestAnnotationProducer"
      perf: "true"
```

try if it helps. The output above looks correct, but I suspect that if this fails randomly then marathon is just not able to get a list of tests, hence your error
