### ISSUE TITLE
Provide a way to run Android tests against specific emulators

### ISSUE THREAD

**Issue by tabletenniser** [MarathonLabs/marathon#804]
In our CI / CD environment, we have a pool of 10 emulators: emu-1, emu-2, ... emu-10. But for a particular run, we only want to use 2 of them (e.g emu-3, emu-4) since there are other concurrent runs happening at the same time using other emulators. Is it possible to add a configuration so that we can provide `-s` flag to the underlying `adb shell am instrument` command?  Some configuration in the YAML file like `emulatorToUse` will be very helpful! Example config I would image:
```
name: ...
outputDir: ...
vendorConfiguration:
  type: "Android"
  emulatorsToUse: "emu-3, emu-4"
```

Looking at the https://docs.marathonlabs.io/ I don't see any configuration on that.
