### ISSUE TITLE
Documentation clarification for parallel-sharding and ANY_SUCCESS

### ISSUE THREAD

**Issue by hborders** [MarathonLabs/marathon#808]
**Describe the bug**
The [Parallel Sharding docs](https://docs.marathonlabs.io/configuration/sharding#parallel-sharding) say:
> Executes each test using available devices. This is the default behaviour.

It isn't clear from the documentation whether the test executes on every pool in parallel or whether each test executes once in an arbitrary pool.

My desired behavior:

I want a test to retry twice within its pool, so the following would be a success for API 31:
```
API 31 test1 run1: fail
API 31 test1 run2: success
```
and the following would be a fail for API 33:
```
API 33 test1 run1: fail
API 33 test1 run2: fail
API 33 test1 run3: fail
```

I tested thusly:
1. I created two Play Store emulators (API 31 and API 33)
1. I used the following configuration:
```yaml
poolingStrategy:
  type: "os-version"
retryStrategy:
  type: "fixed-quota"
  totalAllowedRetryQuota: 100
  retryPerTestQuota: 2
shardingStrategy:
  type: "parallel"
executionStrategy:
  mode: ANY_SUCCESS
```

I created a test that always fails on API 33:
```
        if (Build.VERSION.SDK_INT > Build.VERSION_CODES.S) {
            fail("Always fail API 33")
        }
```

And I observed the following output:
```
Marathon run finished:
Device pool 33:
	3 passed, 1 failed, 0 ignored tests
	Failed tests:
		com.example.FailApi33Test#testfailApi33
	Flakiness overhead: 22960ms
	Raw: 3 passed, 3 failed, 0 ignored, 0 incomplete tests
	Failed tests:
		com.example.FailApi33Test#testfailApi33 failed 3 time(s)
Device pool 31:
	4 passed, 0 failed, 0 ignored tests
	Flakiness overhead: 0ms
	Raw: 4 passed, 0 failed, 0 ignored, 0 incomplete tests
Total time: 0H 2m 57s
```

So, it seems like things work as I expect, but is this intended behavior that I can depend upon?
