### ISSUE TITLE
Manually configurable emulator booting timeout

### ISSUE THREAD

**Issue by IosephKnecht** [MarathonLabs/marathon#835]
**Problem**
Marathon CLI [hardcoded](https://github.com/MarathonLabs/marathon/blob/0.8.4/vendor/vendor-android/src/main/kotlin/com/malinskiy/marathon/android/BaseAndroidDevice.kt#L221) on its side timeout of waiting for the emulator boot state in 30 seconds.
This works fine locally, but on CI it periodically crashes with `DeviceSetupException`.

**Solution**
I would like to explicitly declare a timeout somewhere in configuration file to wait for emulator boot state.

<details>

<summary>For example, so:</summary>

```yaml
---
name: "Marathon"
# omitted lines
vendorConfiguration:
  type: "Android"
  timeoutConfiguration:
    shell: 180.000000000
    listFiles: 20.000000000
    pushFile: 60.000000000
    pushFolder: 60.000000000
    pullFile: 30.000000000
    uninstall: 20.000000000
    install: 20.000000000
    screenrecorder: 200.000000000
    screencapturer: 0.300000000
    socketIdleTimeout: 30.000000000
    portForward: 20.000000000
    #declare booting timeout
    deviceBooting: 180.000000000
```

</details>

**Workaround solution**
At the moment, when running on CI, we poll the `sys.boot_completed` flag in bash scripts ourselves, and only after we make sure that all emulators have switched to boot state can we launch marathon.

<details>

<summary>In scripts, it looks something like this:</summary>

```bash
// https://stackoverflow.com/questions/41151883/wait-for-android-emulator-to-be-running-before-next-shell-command
adb wait-for-device shell 'while [[ -z $(getprop sys.boot_completed) ]]; do sleep 1; done;'
```

</details>

**Additional context**
Interestingly, in marathon version 0.7.6, such an error was practically not reproduced, probably because when setuping device, DeviceSetupException exceptions were not thrown before.
The problem started reproducing with move to marathon 0.8.2 and higher.
[It was in marathon 0.7.6](https://github.com/MarathonLabs/marathon/blob/0.7.6/vendor/vendor-android/base/src/main/kotlin/com/malinskiy/marathon/android/BaseAndroidDevice.kt#L75)
[It became a marathon 0.8.0+](https://github.com/MarathonLabs/marathon/blob/0.8.0/vendor/vendor-android/src/main/kotlin/com/malinskiy/marathon/android/BaseAndroidDevice.kt#L83)
