### ISSUE TITLE
Q: equivalent to -parallel-testing-enabled arg for xcodebuild?

### ISSUE THREAD

**Issue by michaelhuman** [MarathonLabs/marathon#897]
Good day!

I'm trying to configure marathon for iOS testing on a single mac and have no luck. While I have success running raw command `xcodebuild ... -parallel-testing-enabled YES -parallel-testing-worker-count 2 test-without-building`, I'm not able to discover the equivalent configuration for marathon. Docs say we can use fragmentation (which is about running separate processes started from the CI?), shards (which require different macs or sims), and overriden xcodebuild args. The overriden xcodebuild args are not the option because marathon goes to endless loop with parallel-testing-enabled arg.

So can you please give me a hint if there is an option to make parallel tests on a single mac using the only one simulator like this:
```
workers:
  - transport:
      type: local
    devices:
      - type: simulatorProfile
        deviceType: com.apple.CoreSimulator.SimDeviceType.iPhone-SE-3rd-generation
```
Thank you.

**Comment by Malinskiy** [comment]
Hey @michaelhuman. If you use parallel testing then by definition you have to use multiple devices, so in your case
```
workers:
  - transport:
      type: local
    devices:
      - type: simulatorProfile
        deviceType: com.apple.CoreSimulator.SimDeviceType.iPhone-SE-3rd-generation
      - type: simulatorProfile
        deviceType: com.apple.CoreSimulator.SimDeviceType.iPhone-SE-3rd-generation
 .. or more depending on the amount of hardware you have
```

Also it's a bad idea to have 2 drivers in one car here: you can't have `xcodebuild` parallelise your runs and ask `marathon` to do the same. Choose which tool is orchestrating your test runs and configure accordingly.

Fragmentation filter is used for getting distributed test runs that you need to shard without a single point of test distribution, so this is not what you need by the looks of it. I suggest keeping the code args to a minimum until you have a working test run, then iterate from there.

Hope this helps
