### ISSUE TITLE
iOS: Ability to set simulator's locale before tests

### ISSUE THREAD

**Issue by Nemorokr** [MarathonLabs/marathon#906]
**Is your feature request related to a problem? Please describe.**
Need to be able to set simulator's locale before starting tests

**Describe the solution you'd like**
Maybe some sort of config inside Vendor's block of Marathonfile

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by matzuk** [comment]
You can use [xcodebuild test-without-building arguments](https://docs.marathonlabs.io/runner/ios/configure/#xcodebuild-test-without-building-arguments). 

For example, your marathonfile may look like:
```
name: "My application"
outputDir: "derived-data/Marathon"
vendorConfiguration:
  type: "iOS"
  xcodebuildTestArgs:
    "-testLanguage": "fr"
    "-testRegion": "FR"
  bundle:
    application: "sample.zip"
    testApplication: "sampleUITests-Runner.zip"
    testType: xcuitest
```
